import argparse
import configparser
import os
import sys
import pymysql
import datetime
import itertools
import decimal
import smtplib
from email.mime.text import MIMEText
from email.header import Header

__version__ = '0.1'

class ZentaoDialyGen:
  def __init__(self, cfg_filename):
    conf = configparser.ConfigParser()
    conf.read(cfg_filename)
    self._mysql_host = conf.get('zentao_db', 'host')
    self._mysql_port = int(conf.get('zentao_db', 'port'))
    self._mysql_user = conf.get('zentao_db', 'user')
    self._mysql_passwd = conf.get('zentao_db', 'password')
    self._dialy_users = ["'"+i+"'" for i in conf.get('daily', 'users').split(',')]
    self._dialy_to_mails = conf.get('daily', 'to_mails').split(',')
    self._mail_user = conf.get('core', 'mail_user')
    self._mail_host = conf.get('core', 'mail_host')
    self._mail_passwd = conf.get('core', 'mail_password')
    self._today = datetime.datetime.today().strftime('%Y-%m-%d')

  def _get_daily_log(self):
    daily_lines = []
    daily_lines.append("----------------------------------------------------------------------------")
    daily_lines.append("This Below Daily Logs is auto-generated by Zentao Dialy Generator {version}.".format(version=__version__))
    daily_lines.append("Please contact Leon(leon.li@topibd.com) if you have any questions.")
    daily_lines.append("----------------------------------------------------------------------------")
    daily_lines.append('')
    # Connect to the database
    conn = pymysql.connect(host=self._mysql_host,
                           port=self._mysql_port,
                           user=self._mysql_user,
                           password=self._mysql_passwd,
                           db='zentao',
                           cursorclass=pymysql.cursors.DictCursor)
    try:
      with conn.cursor() as cursor:
        sql = """
        SELECT A.account, A.task, B.name AS task_title, A.consumed, B.fromBug
        FROM zt_taskestimate AS A 
        LEFT JOIN zt_task AS B
        ON A.task = B.id
        WHERE account in ({users}) and date = '{date}' and A.consumed > 0
        ORDER BY A.account, A.task
        """
        sql = sql.format(users=','.join(self._dialy_users), date=self._today)
        cursor.execute(sql)
        rs = cursor.fetchall()
        for key, group in itertools.groupby(rs, key=lambda x: x['account']):
          daily_lines.append('{name} {date}'.format(name=key, date=self._today))
          num = 'a'
          for i in list(group):
            consumed = decimal.Decimal(i['consumed'])
            consumed_str = (str(consumed) + ' hours') if consumed > 1 else (str(consumed) + ' hour ')
            line = '{num}). [{consumed}]{is_bug} {task}.'.format(
              num=num, 
              consumed=consumed_str, 
              is_bug=('' if i['fromBug'] == 0 else '[BUG]'),
              task=i['task_title'])
            daily_lines.append(line)
            num = chr(ord(num) + 1)
          daily_lines.append('')
    finally:
      conn.close()
    return '\r\n'.join(daily_lines)

  def gen_daily(self):
    daily_log = self._get_daily_log()
    subject = 'Zentao Dialy {today}'.format(today=self._today)
    message = MIMEText(daily_log, 'plain', 'utf-8')
    message['Subject'] = Header(subject, 'utf-8')
    message['From'] = self._mail_user
    message['To'] = ','.join(self._dialy_to_mails)
    try:
      smtp = smtplib.SMTP()
      smtp.connect(self._mail_host, 25)
      smtp.login(self._mail_user, self._mail_passwd)
      smtp.sendmail(self._mail_user, self._dialy_to_mails, message.as_string())
    except smtplib.SMTPException:
      print("send mail failed.")
      sys.exit(1)

if __name__ == "__main__":
  parser = argparse.ArgumentParser(description='Zentao Dialy Generator')
  parser.add_argument('--version', '-v', action='version', version='%(prog)s ' + __version__)
  parser.add_argument('--config', '-c', type=str, required=False, help='config file', metavar='config.ini')
  args = vars(parser.parse_args())
  cfg_filename = args['config']
  if not cfg_filename:
    print('using config.ini in current directory.')
    cfg_filename = 'config.ini'
  if not os.path.isfile(cfg_filename):
    print('{cfg} not found'.format(cfg=cfg_filename))
    sys.exit(1)
  gen = ZentaoDialyGen(cfg_filename)
  gen.gen_daily()
  
  
